language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
addons:
  apt:
    packages:
      - libav-tools
      - opus-tools
install:
  - pip install -r requirements.txt
  - pip install -r pymumble/requirements.txt
  - pip install unittest2
script:
  - python -m unittest